food_in_mood/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mood.urls')),
]

mood/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import *


urlpatterns = [
    path('', index, name='index'),
    path('recipes', recipes, name='recipes'),
    path('recipes/<str:mood>/', mood_recipes, name='mood_recipes'),
    path('recipe/<int:id>/', recipe, name='recipe'),
    path('journal/', daily_journal, name='journal'),
    path('edit-journal/<int:id>/', edit_journal, name='edit_journal'),
    path('delete-journal/<int:id>/', delete_journal, name='delete_journal'),
    path('profile/', profile, name='profile'),
    path('edit-profile/', edit_profile, name='edit_profile'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('delete-entry/<int:id>/', delete_recent_activity, name="delete_recent_activity"),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mood/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    profile_image = models.ImageField(upload_to='profile_images', null=True, blank=True)

    def __str__(self):
        return self.username

class Mood(models.Model):
    MOOD_CHOICES = [
        ('happy', 'Happy'),
        ('sad', 'Sad'),
        ('stressed', 'Stressed'),
        ('relaxed', 'Relaxed'),
        ('excited', 'Excited'),
        ('anxious', 'Anxious'),
        ('angry', 'Angry'),
        ('content', 'Content'),
        ('bored', 'Bored'),
        ('motivated', 'Motivated'),
        ('grateful', 'Grateful'),
        ('overwhelmed', 'Overwhelmed'),
        ('hopeful', 'Hopeful'),
        ('tired', 'Tired'),
        ('confident', 'Confident'),
    ]

    mood = models.CharField(max_length=100, choices=MOOD_CHOICES, default='happy')

    def __str__(self):
        return self.mood


class MoodEntry(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    mood = models.ForeignKey(Mood, on_delete=models.CASCADE)
    journal_entry = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.mood}'

class Recipe(models.Model):
    mood = models.ForeignKey(Mood, on_delete=models.CASCADE)
    recipe_image = models.ImageField(upload_to='recipe_images', null=True, blank=True)
    title = models.CharField(max_length=150)
    description = models.TextField(null=True, blank=True)
    ingredients = models.TextField()
    instructions = models.TextField()

    def __str__(self):
        return self.title
    

class RecentActivity(models.Model):
    user = models.ForeignKey(CustomUser, models.CASCADE)
    activity = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.activity}'

mood/forms.py
from django import forms
from mood.models import *


class MoodEntryForm(forms.ModelForm):
    class Meta:
        model = MoodEntry
        fields = ['mood', 'journal_entry']


class RegisterForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields =  ['first_name', 'last_name', 'username', 'profile_image','email', 'password']

class LoginForm(forms.Form):
   username = forms.CharField(max_length=100, required=True)
   password = forms.CharField(widget=forms.PasswordInput, required=True)


class EditUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['profile_image', 'first_name', 'last_name', 'email']

mood/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.utils import timezone

# Import Paginator
from django.core.paginator import Paginator


from .models import *
from mood.forms import *
# Create your views here.

@login_required
def index(request):
    moods = Mood.objects.all()

    context = {
        'moods' : moods,
    }
    return render(request, 'index.html', context)

@login_required
def recipes(request):
    recipes = Recipe.objects.all().order_by('?')
    return render(request, 'recipes.html', {'recipes': recipes})

@login_required
def mood_recipes(request, mood):
    _mood = Mood.objects.get(mood = mood)
    recipes = Recipe.objects.filter(mood = _mood)
    if not recipes:
        return redirect('recipes')

    return render(request, 'recipes.html', {"recipes": recipes})

@login_required
def recipe(request, id):
    recipe = Recipe.objects.get(id = id)
    ingredients = recipe.ingredients.split('\n')
    instructions = recipe.instructions.split('\n')
    return render(request, 'recipe.html', {
        'recipe': recipe,
        'ingredients': ingredients,
        'instructions': instructions
    })


@login_required
def daily_journal(request):
    if request.method == "POST":
        journal_form = MoodEntryForm(request.POST)
        if journal_form.is_valid():
            journal = journal_form.save(commit=False)
            journal.user = request.user
            journal.save()
            RecentActivity.objects.create(user = request.user, activity = "You created the journal")
            return redirect('journal')
        print(journal)
    else:
        journal_form = MoodEntryForm()
    
    # Setup Paginator
    p = Paginator(MoodEntry.objects.filter(user = request.user), 2)
    page = request.GET.get('page')
    journals = p.get_page(page)
    
    return render(request, 'journal_entry.html', {"journal" : journal_form, "journals" : journals})


@login_required
def delete_journal(request, id):
    journal = MoodEntry.objects.get(id = id)
    journal.delete()
    RecentActivity.objects.create(user = request.user, activity = "You deleted the journal")
    return redirect('journal')


@login_required
def edit_journal(request, id):
    journal = MoodEntry.objects.get(id = id)
    journal_entry = request.POST.get('edit_journal_entry')
    if journal_entry:
        journal.journal_entry = journal_entry
        journal.save()
    
    return redirect('journal')

@login_required
def profile(request):
    user = CustomUser.objects.get(username = request.user.username)

    #Calculate journal count
    journal_count = MoodEntry.objects.filter(user = user).count()

    #Calculate Average Journals per week
    todays_date = timezone.now()
    start_of_the_year = todays_date.replace(month=1, day=1)
    journals_this_year = MoodEntry.objects.filter(user = user, date__gte = start_of_the_year).count()
    weeks_passed = (todays_date - start_of_the_year).days // 7
    average_journals_per_week = journals_this_year / max(weeks_passed, 1)

    #Recent Activities
    recent_activities = RecentActivity.objects.filter(user = user)

    context = {
        "user" : user,
        "journal_count" : journal_count,
        "average_journals_per_week" : average_journals_per_week,
        "recent_activities" : recent_activities,
    }

    return render(request, 'profile.html', context)

@login_required
def edit_profile(request):
    user = request.user
    if request.method == "POST":
        form = EditUserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
    
    return redirect('profile')


@login_required
def delete_recent_activity(request, id):
    entry = RecentActivity.objects.get(id = id)
    entry.delete()
    return redirect('profile')
    
    
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST, request.FILES)
        print(form.errors)
        if form.is_valid():
            user = form.save(commit=False)  
            user.set_password(form.cleaned_data.get('password'))
            user.save()
            messages.success(request, f"Account created for {user.first_name}!")
            return redirect('login')
        else:
            print("Form Not Valid")
    user_form = RegisterForm()
    return render(request, 'register.html', {"user_form": user_form})


def login_user(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')    
            password = form.cleaned_data.get('password')
            print(username, password)
            user = authenticate(request, username = username, password = password)
            if user is not None:
                login(request, user)
                messages.info(request, f"{request.user.first_name}, You are Logged In!")
                return redirect("index")
            else:
                messages.error(request, "Wrong Credentials!")
                return redirect('login')
        else:
            print("Form Not Valid")
    else:
        login_form = LoginForm()
        return render(request, 'login.html', {"login_form": login_form})
    
def logout_user(request):
    logout(request)
    return redirect('login')

mood/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container h-100">
        {% block content %}
        {% endblock content %}
    </div>

    <script src="{% static 'js/boostrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

mood/templates/footer.html
<footer class="bg-dark text-white py-4 mt-4">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h5>About Us</h5>
                <p>We are a team of passionate individuals dedicated to providing the best recipes and mood journals for our users.</p>
            </div>
            <div class="col-md-4">
                <h5>Quick Links</h5>
                <ul class="list-unstyled">
                    <li><a href="/" class="text-white">Home</a></li>
                    <li><a href="/journal/" class="text-white">Daily Journal</a></li>
                    <li><a href="/recipes" class="text-white">Recipes</a></li>
                    <li><a href="#" class="text-white">My Profile</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <h5>Contact Us</h5>
                <ul class="list-unstyled">
                    <li>Email: info@foodinmood.com</li>
                    <li>Phone: +0000000000</li>
                    <li>Address: Gongabu, Kathmandu</li>
                </ul>
                <div class="social-icons">
                    <a href="#" class="text-white mr-2"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="text-white mr-2"><i class="fab fa-twitter"></i></a>
                    <a href="#" class="text-white mr-2"><i class="fab fa-instagram"></i></a>
                    <a href="#" class="text-white mr-2"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
        </div>
        <div class="text-center mt-3">
            <p>&copy; 2024 FoodInMood. All rights reserved.</p>
        </div>
    </div>
</footer>

mood/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column min-vh-100 justify-content-between" style="height: 100vh;">
    {% include 'navbar.html' %}

    <main class="flex-fill d-flex justify-content-center align-items-center" >
        <div class="box p-4 text-center" style="max-width: 600px; width: 100%;">
            <h2 class="mb-4">Select Your Mood</h2>
            <div class="row">
                {% for mood in moods %}
                <div class="col-md-4 col-6 mb-3">
                    <a href="{% url 'mood_recipes' mood=mood %}" class="btn btn-outline-primary w-100">{{ mood }}</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </main>

    {% include 'footer.html' %}
</div>
{% endblock content %}

mood/templates/journal_entry.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{% include 'navbar.html' %}

<div class="container mt-4">
    <h2>Daily Journal</h2>
    <form action="" method="POST" class="mb-4">
        {% csrf_token %}
        {{ journal|crispy }}
        <button type="submit" class="btn btn-success mt-2">Post</button>
    </form>

    <div class="mt-4">
        <div class="mb-4">
            <div class="list-group">
                {% if journals %}
                {% for journal in journals %}
                <div
                    class="list-group-item list-group-item-action mb-2 d-flex justify-content-between align-items-center">
                    <div class="d-flex flex-column flex-grow-1">
                        <h5 class="mb-1">{{journal}} </h5>
                        <div class="journal-content">
                            <p class="mb-1" id="journal_content_entry">{{journal.journal_entry}}</p>
                            <form action="{% url 'edit_journal' journal.id %}" id="edit_journal_form" method="post" class="mb-2">
                                {% csrf_token %}
                                <textarea name="edit_journal_entry"
                                    class="form-control journal-entry-edit d-none"
                                    id="edit_journal_entry_textarea" rows="1">{{journal.journal_entry}}</textarea>
                            </form>
                        </div>
                        <small class="text-muted">{{journal.date}} | <strong>Mood:</strong>
                            {{journal.mood}}</small>
                    </div>
                    <div class="btn-group d-flex flex-column justify-content-center gap" role="group">
                        <button type="submit" class="btn btn-warning btn-sm w-100 mb-2"
                            id="edit_journal">Edit</button>
                        <form action="{% url 'delete_journal' journal.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger delete_journal btn-sm w-100">Delete</button>
                        </form>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <div
                    class="list-group-item list-group-item-action mb-2 d-flex justify-content-between align-items-center">
                    <div class="d-flex flex-column flex-grow-1">
                        <h5 class="mb-1"> No Journal Yet. </h5>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if journals.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo; First</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ journals.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">Previous</span>
                </a>
            </li>
            {% endif %}

            {% for num in journals.paginator.page_range %}
            {% if journals.number == num %}
            <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% elif num > journals.number|add:'-3' and num < journals.number|add:'3' %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}

            {% if journals.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ journals.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">Next</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ journals.paginator.num_pages }}" aria-label="Last">
                    <span aria-hidden="true">Last &raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% include 'footer.html' %}
</div>

{% endblock content %}

mood/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </div>
    {% endif %} <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ login_form|crispy }}
        <button type="submit" class="btn btn-info mt-3">Login</button><br><br>
        <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
    </form>
</div>
{% endblock content %}

mood/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">Mood Journal</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mx-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'journal' %}">Daily Journal</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'recipes' %}">Recipes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' %}">My Profile</a>
            </li>
        </ul>
        <span class="navbar-text mx-3">
            {% if user.first_name %}
            Welcome, {{ user.first_name }}!
            {% else %}
            Welcome, {{ user.username }}!
            {% endif %}
        </span>
        <a class="btn btn-outline-primary" id="logout" href="#">Logout</a>
        <form class="d-none" id="logout_form" action="{% url 'logout' %}" method="post">
            {% csrf_token %}
        </form>
    </div>
</nav>

mood/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'navbar.html' %}

<div class="container mt-4">
    <h2>Profile</h2>
<hr>
    <!-- Flex Container for Profile Info and Edit Section -->
    <div class="d-flex flex-row justify-content-between">
        <!-- Profile Info and Journal Statistics-->
        <div class="profile-and-stats flex-grow-1 mb-5">
            <div class="profile-info">
                {% if user.profile_image %}
                    <img src="{{ user.profile_image.url }}" alt="Profile Image" class="img-fluid rounded-circle" style="width: 150px; height: 150px;">
                {% else %}
                    <img src="{% static 'default-profile-image.png' %}" alt="Default Profile Image" class="img-fluid rounded-circle" style="width: 150px; height: 150px;">
                {% endif %}
                <h3 class="mt-2">{{ user.first_name }} {{ user.last_name }}</h3>
                <p>Email: {{ user.email }}</p>
                <a href="#" class="btn btn-primary" id="edit-profile-button">Edit Profile</a>
            </div>

            <!-- Journal Statistics -->
            <div class="mt-4">
                <h4>Journal Statistics</h4>
                <p>Total Journals: {{ journal_count }}</p>
                <p>Average Journals per Week: {{ average_journals_per_week|floatformat:2 }}</p>
            </div>
        </div>

        <!-- Edit Profile Form -->
        <div class="edit-profile d-none" id="edit-profile">
            <h4>Edit Profile</h4><hr>
            <form method="post" enctype="multipart/form-data" action="{% url 'edit_profile' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_profile_image" class="form-label">Profile Image:</label>
                    <input type="file" class="form-control" id="id_profile_image" name="profile_image">
                </div>
                <div class="mb-3">
                    <label for="id_first_name" class="form-label">First Name:</label>
                    <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ user.first_name }}">
                </div>
                <div class="mb-3">
                    <label for="id_last_name" class="form-label">Last Name:</label>
                    <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ user.last_name }}">
                </div>
                <div class="mb-3">
                    <label for="id_email" class="form-label">Email:</label>
                    <input type="email" class="form-control" id="id_email" name="email" value="{{ user.email }}">
                </div>
                <button type="submit" class="btn btn-primary">Save Changes</button>
            </form>
        </div>
    </div>

    <!-- Recent Activities -->
    <div class="mt-4">
        <h4>Recent Activities</h4>
        <ul class="list-group">
            {% for entry in recent_activities %}
                <li class="list-group-item d-flex justify-content-between">
                    <span class="d-flex align-items-center">{{ entry.activity }}: <strong> {{ entry.date }}</strong></span>
                    <form action="{% url 'delete_recent_activity' entry.id %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-warning delete-recent-entry" >Delete</button>
                    </form>
                </li>

            {% empty %}
                <li class="list-group-item">No recent activities found.</li>
            {% endfor %}
        </ul>
    </div>
</div>

{% include 'footer.html' %}

{% endblock content %}

mood/templates/recipe.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}

<div class="container mt-4">
    <h2><strong>{{ recipe.title }}</strong></h2>
    {% if recipe.recipe_image %}
    <img src="{{ recipe.recipe_image.url }}" class="img-fluid mb-4 d-flex m-auto" height="500" width="500" alt="{{ recipe.title }}">
    {% endif %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title"><strong>Description</strong></h5>
            <p class="card-text">{{ recipe.description }}</p>

            <h5 class="card-title"><strong>Ingredients</strong></h5>
            <ul class="list-group list-group-flush mb-3">
                {% for ingredient in ingredients %}
                <li class="list-group-item">{{ ingredient }}</li>
                {% endfor %}
            </ul>

            <h5 class="card-title"><strong>Instructions</strong></h5>
            <ol class="list-group list-group-flush mb-3">
                {% for instruction in instructions %}
                <li class="list-group-item">{{ instruction }}</li>
                {% endfor %}
            </ol>
        </div>
    </div>
</div>
{% include 'footer.html' %}

{% endblock content %}

mood/templates/recipes.html
{% extends 'base.html' %}

{% block content %}

{% include 'navbar.html' %}

<div class="container my-5">
    <div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;">
        <div class="box p-5 w-100">
            <h2 class="text-center mb-4">Recipes</h2>
            <div class="row">
                {% for recipe in recipes %}
                <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                    <div class="card h-100 p-3 w-100">
                        <img src="{{ recipe.recipe_image.url }}" alt="{{ recipe.title }}" class="card-img-top fixed-size-image">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title">{{ recipe.title }}</h5>
                            <p class="card-text flex-grow-1">{{ recipe.description }}</p>
                            <a href="{% url 'recipe' recipe.id %}" class="btn btn-outline-primary mt-auto">View Recipe</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

                                                                                                                                                





{% include 'footer.html' %}

{% endblock content %}

mood/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
    <h2>Register</h2>
    <form method="post">
        {% csrf_token %}
        {{ user_form|crispy }}
        <button type="submit" class="btn btn-info mt-3">Login</button><br><br>
        <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>
    </form>
</div>
{% endblock content %}